# Generated by Django 2.1.2 on 2018-10-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jta', '0002_jsast_original_script'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParseScriptAst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_js', models.TextField(blank=True, null=True)),
                ('output_ast', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='jsast',
            name='tokenize',
        ),
    ]
