# Generated by Django 2.1.2 on 2018-10-03 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jta', '0003_auto_20181003_1310'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JsAst',
        ),
    ]
