# Generated by Django 2.1.2 on 2018-10-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jta', '0004_delete_jsast'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsescriptast',
            name='comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parsescriptast',
            name='jsx',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parsescriptast',
            name='loc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parsescriptast',
            name='range',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parsescriptast',
            name='tokens',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parsescriptast',
            name='tolerant',
            field=models.BooleanField(default=False),
        ),
    ]
