# Generated by Django 2.1.2 on 2018-10-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jta', '0005_auto_20181003_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='AstParse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_ast', models.TextField(blank=True, null=True)),
                ('output_js', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='ParseScriptAst',
            new_name='ScriptParse',
        ),
    ]
