# Generated by Django 2.1.2 on 2018-11-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jta', '0006_auto_20181004_0320'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateNewScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_js', models.TextField(blank=True, null=True)),
                ('output_ast', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
